# Generated by Django 3.1.7 on 2021-04-22 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='intTravel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='travelDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
