# Generated by Django 3.1.7 on 2021-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0002_auto_20210422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travelDate',
            field=models.DateField(),
        ),
    ]
