# Generated by Django 3.1.7 on 2021-04-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0003_auto_20210422_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='setuStatus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
