# Generated by Django 3.1.7 on 2021-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0004_ticket_setustatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
