# Generated by Django 3.1.7 on 2021-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0005_ticket_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='dest',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='report',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
