# Generated by Django 3.1.7 on 2021-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0006_auto_20210422_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='train',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
