# Generated by Django 3.1.7 on 2021-04-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0008_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
