# Generated by Django 3.1.7 on 2021-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0011_auto_20210423_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='', upload_to='media/aadhar'),
        ),
    ]
