# Generated by Django 3.1.7 on 2021-04-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketCRUD', '0012_auto_20210423_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
